# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Auth-Yubikey_Decrypter
version:      0.05
version_from: lib/Auth/Yubikey_Decrypter.pm
installdirs:  site
requires:
    Crypt::Rijndael:               1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
